version: '3.7'
services:
  game:
    image: 2357gi/fujihalab-craft
    ports:
      - "25565:25565"
    expose:
      - 25565
    volumes:
      - data:/opt/app

volumes:
  data:
# if you has local-persist docker plugin,
# del # and baind host dir
#     driver: local-persist
#     driver_opts:
#       mountpoint: ./server_data
